apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cookwherever-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # specify the name of the global IP address resource to be associated with the HTTP(S) Load Balancer.
    kubernetes.io/ingress.global-static-ip-name: 34.125.64.174
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # controls whether the ingress is modified ‘in-place’,
    # or a new one is created specifically for the HTTP01 challenge.
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  tls: # < placing a host in the TLS config will indicate a certificate should be created
    - hosts:
      - cookwherever.com
      - recipes.cookwherever.com
      secretName: cookwherever-tls-secret
  rules:
    - host: cookwherever.com
      http:
        paths:
          - backend:
              service:
                name: wiki
                port:
                  number: 80
            path: /
            pathType: Prefix
    - host: recipes.cookwherever.com
      http:
        paths:
          - backend:
              service:
                name: oathkeeper
                port:
                  number: 4455
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
